<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Scheduler.Application/Scheduler.Application.csproj" />
    <ProjectReference Include="../../src/Scheduler.Infrastructure.Xlsx/Scheduler.Infrastructure.Xlsx.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="DocumentFormat.OpenXml" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
</Project>
